name: Build & Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Obter código
        run: echo "Obter código"
      - name: Instalar DEPs
        run: echo "Instalar DEPs"
      - name: Rodar TEST
        run: echo "Rodar TEST"
    
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Obter código
        run: echo "Obter código"
      - name: Instalar DEPs
        run: echo "Instalar DEPs"
      - name: Rodar TEST
        run: echo "Rodar TEST"
